services:
  app:
    entrypoint:
    - sleep
    - infinity
    image: jupyter/tensorflow-notebook
    init: true
    volumes:
    - type: bind
      source: /var/run/docker.sock
      target: /var/run/docker.sock